version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db:5432/adfly_dev
      - SECRET_KEY_BASE=your_secret_key_base_here
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/deps
      - /app/_build
    command: mix phx.server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adfly_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 