version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db:5432/adfly_dev
      - SECRET_KEY_BASE=your_secret_key_base_here
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    command: mix phx.server

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adfly_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 